[target.thumbv8m.main-none-eabihf]
runner = 'probe-rs run --chip MIMXRT685SFVKB --no-catch-hardfault --no-catch-reset --preverify --verify'

rustflags = [
  "-C", "linker=arm-none-eabi-ld",
]

[build]
target = "thumbv8m.main-none-eabihf" # Cortex-M33

[env]
DEFMT_LOG = "trace"
